//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mosico.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4278190080")]
        public uint CellColor {
            get {
                return ((uint)(this["CellColor"]));
            }
            set {
                this["CellColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double CellSize {
            get {
                return ((double)(this["CellSize"]));
            }
            set {
                this["CellSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double InitialCircleSize {
            get {
                return ((double)(this["InitialCircleSize"]));
            }
            set {
                this["InitialCircleSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gforce_longitudinal")]
        public string CarlaSizeBindingField {
            get {
                return ((string)(this["CarlaSizeBindingField"]));
            }
            set {
                this["CarlaSizeBindingField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.7")]
        public double CarlaSizeBindingScale {
            get {
                return ((double)(this["CarlaSizeBindingScale"]));
            }
            set {
                this["CarlaSizeBindingScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double MaxCircleSize {
            get {
                return ((double)(this["MaxCircleSize"]));
            }
            set {
                this["MaxCircleSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gforce_lateral")]
        public string CarlaOffsetBindingField {
            get {
                return ((string)(this["CarlaOffsetBindingField"]));
            }
            set {
                this["CarlaOffsetBindingField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double CarlaOffsetBindingScale {
            get {
                return ((double)(this["CarlaOffsetBindingScale"]));
            }
            set {
                this["CarlaOffsetBindingScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double SizeChangeDamping {
            get {
                return ((double)(this["SizeChangeDamping"]));
            }
            set {
                this["SizeChangeDamping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double OffsetChangeDamping {
            get {
                return ((double)(this["OffsetChangeDamping"]));
            }
            set {
                this["OffsetChangeDamping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AccBdyX")]
        public string ValtraImuSizeBindingField {
            get {
                return ((string)(this["ValtraImuSizeBindingField"]));
            }
            set {
                this["ValtraImuSizeBindingField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double ValtraImuSizeBindingScale {
            get {
                return ((double)(this["ValtraImuSizeBindingScale"]));
            }
            set {
                this["ValtraImuSizeBindingScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AccBdyY")]
        public string ValtraImuOffsetXBindingField {
            get {
                return ((string)(this["ValtraImuOffsetXBindingField"]));
            }
            set {
                this["ValtraImuOffsetXBindingField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AccBdyZ")]
        public string ValtraImuOffsetYBindingField {
            get {
                return ((string)(this["ValtraImuOffsetYBindingField"]));
            }
            set {
                this["ValtraImuOffsetYBindingField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double ValtraImuOffsetBindingScale {
            get {
                return ((double)(this["ValtraImuOffsetBindingScale"]));
            }
            set {
                this["ValtraImuOffsetBindingScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DataSource {
            get {
                return ((int)(this["DataSource"]));
            }
            set {
                this["DataSource"] = value;
            }
        }
    }
}
